import { randomUUID } from "crypto";
import type { MeterInfo, MeterOtherInfo, JsonObject } from "./types";

export function newId(): string {
  return randomUUID().replace(/-/g, "");
}

export function emptyMeter(seat: number): MeterInfo {
  const id = newId();
  return {
    isCheck: true,
    MeterSeat: String(seat),
    Name: "",
    MeterNo: "",
    MeterTS: "",
    Factory: "",
    FactoryAddr: "",
    FactoryTel: "",
    MeterAssetCoding: "",
    MeterAddr: "",
    MeterBatch: "",
    MeterLevel: "",
    Un: "220",
    Imax: "",
    Imin: "",
    Ist: "",
    Itr: "",
    Freq: "50",
    ActivePulseConstant: "",
    ReactivePulseConstant: "",
    ActivePowerAccuracyClass: 0,
    ReactivePowerAccuracyClass: 0,
    EnergyDecimalDigits: 2,
    CT: "1",
    PT: "1",
    Phase: 0,
    MeterProtocol: 1,
    MeterSort: 1,
    MeterType: 0,
    Type: 1,
    ReactiveIb: "0",
    IP: "",
    User: "",
    InspectionUnit: "",
    InspectionUnitAddr: "",
    InspectionUnitTel: "",
    ProductionDate: "",
    RegistrationTime: "",
    TemperatureMax: "NaN",
    TemperatureMin: "NaN",
    ID: id,
  };
}

export function emptyOtherInfo(meterId: string, seat: number): MeterOtherInfo {
  return {
    ID: meterId,
    BarCode: "",
    LeadSealFirst: "",
    LeadSealSecond: "",
    MeterSeat: seat,
  };
}

export function emptySchemeGroup(): JsonObject {
  return {
    ID: newId(),
    BH: "",
    Name: "",
    ItemName: "",
    ItemCode: "",
    ItemBH: "",
    ItemID: "",
    ProID: "",
    ProBH: "",
    ProName: "",
    OrderIndex: 0,
    ItemOrderIndex: 0,
    DianYa: "",
    DianLiu: "",
    BDianYa: "",
    BDianLiu: "",
    CDianYa: "",
    CDianLiu: "",
    GLYS: "1.0",
    pinlv: "50",
    XiangBie: "",
    ErrorItem: "",
    CiShu: 2,
    RMax: 0.5,
    RMin: -0.5,
    TaiCha: 1.0,
    QDtime: 1.0,
    QuanShu: 0,
    Electricity: "0",
    DelFlag: 0,
    JCtype: 0,
    PID: "",
    PointID: "",
    DianliuDang: "",
    Remark: "",
    TestData: "",
  };
}

export function emptyTestItem(): JsonObject {
  return {
    ID: newId(),
    BH: "",
    Code: "",
    Name: "",
    OrderIndex: 0,
    DelFlage: 0,
    JCtype: 0,
    PID: "",
  };
}

export function emptyResultDetail(): JsonObject {
  return {
    ID: newId(),
    MeterID: "",
    MeterBh: "",
    MeterAddr: "",
    MeterSeat: "",
    MeterName: "",
    MeterAssetCoding: "",
    MeterBatch: "",
    MeterTS: "",
    Factory: "",
    ItemID: "",
    ItemCode: "",
    ItemName: "",
    PointID: "",
    PointCode: "",
    PointName: "",
    TestItem: "",
    Phase: "",
    PowerFactor: "",
    Freq: "50",
    VoltA: "",
    VoltB: "",
    VoltC: "",
    CurrA: "",
    CurrB: "",
    CurrC: "",
    Result: "",
    ResultLog: "",
    AverageResult: "",
    FinalResults: "",
    RMax: "",
    RMin: "",
    CiShu: "2",
    QuanShu: "0",
    Electricity: "0",
    StartTime: "",
    EndTime: "",
    ProID: "",
    ProBH: "",
    ProName: "",
    OrderIndex: 0,
    DgvIndex: 0,
    MeterSort: 0,
    IsSaveFlag: 0,
    Code: "",
    CreateUser: "",
    CreateUserID: "",
    TaiCha: "",
    Remark1: "",
    Remark2: "",
    Remark3: "",
    Remark4: "",
  };
}
